### ISSUE TITLE
Wrong Number of Arguments?

### ISSUE THREAD

**Issue by TyRichards** [rubymotion/ib#57]
Any idea how to resolve this? When I follow the install instructions and enter rake ib:open I get this error:

$ rake ib:open
rake aborted!
wrong number of arguments (0 for 1..2)
/Users/tyrichards/.rvm/gems/ruby-2.0.0-p353/gems/xcodeproj-0.14.1/lib/xcodeproj/project.rb:57:in `initialize'
/Users/tyrichards/.rvm/gems/ruby-2.0.0-p353/gems/ib-0.2.7/lib/ib/project.rb:3:in`new'
/Users/tyrichards/.rvm/gems/ruby-2.0.0-p353/gems/ib-0.2.7/lib/ib/project.rb:3:in `write'
/Users/tyrichards/.rvm/gems/ruby-2.0.0-p353/gems/ib-0.2.7/lib/ib/tasks.rb:11:in`block (2 levels) in <top (required)>'
/Users/tyrichards/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/Users/tyrichards/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => ib:open => ib:project

**Comment by andreheijstek** [comment]
I'm getting the same error at the moment: Don't know how to build task 'ib'
I use ib 0.4.4 and xcodeproj 0.23.1
Could this be a similar problem?
