### ISSUE TITLE
Subfolders in /resources don't seem to be referenced correctly in resulting xcode project

### ISSUE THREAD

**Issue by markrickert** [rubymotion/ib#78]
Here's my folder structure...

![screenshot 2015-01-20 12 35 50](https://cloud.githubusercontent.com/assets/139261/5822305/e7b680e6-a0a0-11e4-9b6f-c351d792884a.png)

And the resulting xcode project has the files in red.

Moving the files out of the subfolder makes the xcode file reference turn black and the file is accessible. It seems like xcode isn't getting the correct path for the resource file:

```xml
<key>9CBABA3531C7B6D591F332AE</key>
<dict>
  <key>includeInIndex</key>
  <string>1</string>
  <key>isa</key>
  <string>PBXFileReference</string>
  <key>lastKnownFileType</key>
  <string>file.xib</string>
  <key>path</key>
  <string>ActivityFavouriteTableViewCell.xib</string>
  <key>sourceTree</key>
  <string>&lt;group&gt;</string>
</dict>
```
Should be: 

```xml
<key>9CBABA3531C7B6D591F332AE</key>
<dict>
  <key>includeInIndex</key>
  <string>1</string>
  <key>isa</key>
  <string>PBXFileReference</string>
  <key>lastKnownFileType</key>
  <string>file.xib</string>
  <key>name</key>
  <string>ActivityFavouriteTableViewCell.xib</string>
  <key>path</key>
  <string>assets/ActivityFavouriteTableViewCell.xib</string>
  <key>sourceTree</key>
  <string>&lt;group&gt;</string>
</dict>
```

**Comment by colinta** [comment]
My guess, just taking a quick look: <https://github.com/rubymotion/ib/blob/master/lib/ib/project.rb#L106>

```ruby
group.new_reference(File.basename(file))  # <= maybe this should just remove the "resources/" prefix
```

**Comment by markrickert** [comment]
I've got a fix. Looking to see how to test it... :)

**Comment by colinta** [comment]
Nice :-)

**Comment by markrickert** [comment]
It doesn't seem as though the project tests the actual xcode project folder structure output. I'll submit the PR and you can check it out and merge if you don't think specs are needed.
