### ISSUE TITLE
[Bug] Invalid class headers in stubs.h when subclassing framework files

### ISSUE THREAD

**Issue by Bodacious** [rubymotion/ib#85]
My app contains our own internal framework for connecting to our API client (similar to Motion-Resource)

The app's file structure is:

    app/
      models/
        image.rb # this is a subclass of KatanaResource::Base
        venue.rb # this is a subclass of KatanaResource::Base

    lib/
      katana_resource.rb
      katana_resource/
        base.rb 
        # ...

When I run `rake ib` it creates the **ib.xcodeproj** fine. However, since the base class for Image and Venue are defined in the `lib` directory, they're not loaded by **ib**. I get this feedback from Xcode:

This is a screenshot of the error message: https://www.dropbox.com/s/dizg3djquowd1jz/Screenshot%202015-10-28%2010.12.35.png?dl=0

The problem this creates, is that the IB outlets I've defined in my views are not visible under the outlets section in the **Connections inspector**. 

I can rectify the issue by either: 

a) Manually modifying the Stubs files and removing the invalid class definitions
b) Modifying `project.rb:24` to look like:

      def app_files
        @app_files ||= motion_config.files.select do |file|
          file =~ /(^(\.\/)?app\/|katana)/
        end
      end
c) Adding an empty file in app/ containing the name of the *missing* class

**Comment by colinta** [comment]
You can set `app_files` to whatever you want by customizing the project instance (https://github.com/rubymotion/ib#customizing-ibproject)

```ruby
IB::RakeTask.new do |project|
  project.app_files = motion_config.files.select do |file|
      file =~ /(^(\.\/)?app\/|katana)/
    end
end
```

**Comment by Bodacious** [comment]
Magical. Thanks!
