### ISSUE TITLE
How much of this can I add to my gitignore file?

### ISSUE THREAD

**Issue by Bodacious** [rubymotion/ib#86]
First of all, 💟 IB. Well done!

Each time I run my app though, almost all of the `xib` files are updated (whether any changes are made or not). This makes my git repo pretty large. 

They're changes in the nib binary files (which `git diff` won't show)

```
Binary files a/resources/nibs/Storyboard.storyboardc/AvailabilityController.nib and b/resources/nibs/Storyboard.storyboardc/AvailabilityController.nib differ
```

Can I exclude any of these from git without losing the portability of my code?

**Comment by colinta** [comment]
You definitely don't need to include the `nib` files in source control, only the `xib`s.

**Comment by Bodacious** [comment]
On close inspection, I actually thought I'd removed them from the repo but the `.gitignore` wasn't properly configured. 

Thanks
